import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
const mainUrl = new URL('../js/main.js', import.meta.url);
const planUrl = new URL('../js/components/vacation-plan.js', import.meta.url);
const holidayCalendarUrl = new URL('../js/models/holiday-calendar.js', import.meta.url);
const appUrl = new URL('../js/modules/vacation-app.js', import.meta.url);
const adminUrl = new URL('../js/admin.js', import.meta.url);
const main = readFileSync(mainUrl, 'utf8');
const plan = readFileSync(planUrl, 'utf8');
const holidayCalendar = readFileSync(holidayCalendarUrl, 'utf8');
const app = readFileSync(appUrl, 'utf8');
const template = readFileSync(new URL('../templates/index.php', import.meta.url), 'utf8');
const source = [main, plan, holidayCalendar, app, template].join('\n');
for (const contract of ['adu-year-table', 'approved', 'data-action', 'set-status', 'client.request', '/api/teams/', 'requestFor', "['organization', 'Büros und Fachgruppen']", "document.createElement('optgroup')", 'adu-integration-status', 'Dienstkonflikte werden nicht automatisch geprüft']) if (!source.includes(contract)) throw new Error(`Frontendvertrag fehlt: ${contract}`);
for (const contract of ['class VacationPlan', 'renderChrome()', 'renderPlan()', 'renderOwnRequests()', 'showConflicts(error)']) if (!plan.includes(contract)) throw new Error(`Plan-Komponentenvertrag fehlt: ${contract}`);
for (const contract of ['this.holidays.schoolHolidayName(', 'this.holidays.publicHolidayName(', 'renderSchoolHolidayBand(', 'renderPublicHolidayBand(', 'adu-school-holiday-row', 'adu-public-holiday-row', 'is-school-holiday', 'is-public-holiday']) if (!plan.includes(contract)) throw new Error(`Ferien-/Feiertags-Darstellungsvertrag fehlt: ${contract}`);
for (const contract of ['class VacationApp', 'bindEvents()', 'async loadYear()', 'async changeStatus(event)', 'async createOwn(event)', 'async deleteOwn(event)']) if (!app.includes(contract)) throw new Error(`App-Controller-Vertrag fehlt: ${contract}`);
for (const contract of ["\\OCP\\Util::addScript('adurlaub', 'models/holiday-calendar')", "\\OCP\\Util::addScript('adurlaub', 'components/vacation-plan')", "\\OCP\\Util::addScript('adurlaub', 'modules/vacation-app')", "\\OCP\\Util::addScript('adurlaub', 'main')"]) if (!template.includes(contract)) throw new Error(`Skript-Reihenfolge fehlt: ${contract}`);
for (const removed of ['/api/settings', 'adu-tab-settings', "showView('settings')"]) if (source.includes(removed)) throw new Error(`Organisationsweite Einstellung liegt noch im Urlaubs-Frontend: ${removed}`);
if (!app.includes('const formElement = event.currentTarget') || !app.includes('formElement.reset()') || app.includes('event.currentTarget.reset()')) throw new Error('Urlaubsformular verliert seinen Formularbezug nach dem asynchronen Speichern.');
if (!main.includes('new window.AdUrlaub.modules.VacationApp') || !main.includes('.start()')) throw new Error('main.js ist kein schlanker Bootstrap.');
for (const url of [mainUrl, holidayCalendarUrl, planUrl, appUrl, adminUrl]) execFileSync('node', ['--check', url.pathname], {stdio:'inherit'});
execFileSync(process.execPath, [new URL('./js/holiday-calendar-smoke.mjs', import.meta.url).pathname], {stdio:'inherit'});
execFileSync(process.execPath, [new URL('./js/admin-access-smoke.mjs', import.meta.url).pathname], {stdio:'inherit'});
console.log('AD Urlaub JavaScript tests passed');
